#cloud-config
package_update: true
package_upgrade: true
package_install:
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common

# Install Docker
runcmd:
  # Install Docker
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - apt-get update
  - apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin

  # Create application directory
  - mkdir -p /opt/sushi7
  - chmod 755 /opt/sushi7

  # Configure firewall
  - ufw allow 22/tcp
  - ufw allow 9292/tcp
  - ufw --force enable

  # Set up automatic updates
  - echo "0 4 * * * cd /opt/sushi7 && docker compose pull && docker compose up -d" | crontab -

  # Create systemd service for automatic restart
  - echo '[Unit]
Description=Sushi7 Bot Service
Requires=docker.service
After=docker.service

[Service]
Type=oneshot
RemainAfterExit=yes
WorkingDirectory=/opt/sushi7
ExecStart=/usr/bin/docker compose up -d
ExecStop=/usr/bin/docker compose down
TimeoutStartSec=0

[Install]
WantedBy=multi-user.target' > /etc/systemd/system/sushi7.service

  - systemctl enable sushi7.service

# Set up automatic security updates
security:
  ssh_pwauth: false
  disable_root: true
  allow_ssh: true
  ssh_authorized_keys:
    - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK9Nm3eDjSqOCgWtYtuJOfDU2AOcxmfWihpI9l3ll3OJ hetzner_server 